name: CI

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ssh key generate
      run: echo "$SSH_DEVELOPMENT_KEY" > key && chmod 600 key
      env:
        SSH_DEVELOPMENT_KEY: ${{ secrets.SSH_DEVELOPMENT_KEY }}
    - name: Making cache for prepare
      id: prepare-deploy-cache
      uses: actions/cache@v1
      with:
        path: prepare-deploy
        key: ${{ runner.os }}-prepare-deploy-test-key-128903adlas@!&(*1
    - name: Making tar for Deploy
      if: steps.prepare-deploy-cache.outputs.cache-hit != 'true'
      run: bash ./prepare_deploy.sh development
    #- name: Deploying
    #  run: bash ./exec_deploy_development.sh key
